export const MODES = {
  EASY: {
    id: 'EASY',
    label: 'Easy',
    time: 420,
    hints: 3,
    base: 100,
    speed: 150,
    multiplier: 1.0,
  },
  HARD: {
    id: 'HARD',
    label: 'Hard',
    time: 360,
    hints: 2,
    base: 175,
    speed: 250,
    multiplier: 1.5,
  },
  EXTREME: {
    id: 'EXTREME',
    label: 'Extreme',
    time: 300,
    hints: 1,
    base: 250,
    speed: 400,
    multiplier: 2.0,
  },
}

export const CHALLENGES = {
  EASY: [
    {
      cat: 'PATTERN ANALYSIS',
      title: 'SEQUENCE LOCK',
      tag: 'E-01',
      streamText: 'DATA STREAM // E-01',
      cipherText: '3   6   9   12   15   ?',
      subPrompt: 'IDENTIFY THE NEXT VALUE',
      options: ['17', '18', '19', '21'],
      answer: '18',
      hint: 'The sequence increases by the same amount each time.',
      explanation: 'Each step adds 3. 15 + 3 = 18.',
    },
    {
      cat: 'BINARY SYSTEMS',
      title: 'ASCII ACCESS',
      tag: 'E-02',
      streamText: 'TERMINAL NODE // E-02',
      cipherText: '01000010',
      subPrompt: 'DECODE THE ASCII CHARACTER',
      options: ['A', 'B', 'C', 'D'],
      answer: 'B',
      hint: 'Convert the 8-bit value to decimal.',
      explanation: '01000010 is decimal 66, which is ASCII B.',
    },
    {
      cat: 'CRYPTANALYSIS',
      title: 'SHIFTED MESSAGE',
      tag: 'E-03',
      streamText: 'INTERCEPT // E-03',
      cipherText: 'KHOOR',
      metaInfo: 'SHIFT OFFSET: +3',
      subPrompt: 'DECODE THE MESSAGE',
      options: ['HELLO', 'WORLD', 'CODEX', 'ALERT'],
      answer: 'HELLO',
      hint: 'Move every encrypted letter three places backward.',
      explanation: 'KHOOR shifted back by 3 becomes HELLO.',
    },
    {
      cat: 'NUMBER LOGIC',
      title: 'CALCULATION NODE',
      tag: 'E-04',
      streamText: 'CALCULATION NODE // E-04',
      cipherText: '5 × 4 + 6 = ?',
      subPrompt: 'APPLY STANDARD OPERATION ORDER',
      options: ['26', '46', '50', '34'],
      answer: '26',
      hint: 'Multiplication is evaluated before addition.',
      explanation: '5 × 4 = 20, then 20 + 6 = 26.',
    },
    {
      cat: 'CODE DEDUCTION',
      title: 'ACCESS TOKEN',
      tag: 'E-05',
      streamText: 'SECURITY LOG // E-05',
      hintBox: [
        'CODE HAS 4 DIGITS',
        'FIRST DIGIT = 7',
        'SECOND = FIRST - 2',
        'THIRD = SECOND + 1',
        'FOURTH = THIRD + 2',
      ],
      subPrompt: 'SELECT THE TOKEN',
      options: ['7546', '7568', '7658', '7456'],
      answer: '7568',
      hint: 'Calculate each digit from the previous one.',
      explanation: '7 → 5 → 6 → 8. The token is 7568.',
    },
  ],

  HARD: [
    {
      cat: 'PATTERN ANALYSIS',
      title: 'DOUBLE DELTA',
      tag: 'H-01',
      streamText: 'DATA STREAM // H-01',
      cipherText: '4   7   13   22   34   ?',
      subPrompt: 'FIND THE NEXT VALUE',
      options: ['47', '48', '49', '50'],
      answer: '49',
      hint: 'Look at the gaps between consecutive numbers.',
      explanation: 'Differences are +3, +6, +9, +12. The next gap is +15, giving 49.',
    },
    {
      cat: 'CRYPTANALYSIS',
      title: 'SHIFTED SIGNAL',
      tag: 'H-02',
      streamText: 'INTERCEPT // H-02',
      cipherText: 'FRGH',
      metaInfo: 'SHIFT OFFSET: +3',
      subPrompt: 'DECODE THE SIGNAL',
      options: ['CODE', 'DATA', 'CELL', 'LOCK'],
      answer: 'CODE',
      hint: 'Move every encrypted letter three places backward.',
      explanation: 'F→C, R→O, G→D, H→E. The message is CODE.',
    },
    {
      cat: 'LOGIC MATRIX',
      title: 'SYSTEM PRIORITY',
      tag: 'H-03',
      streamText: 'OPERATIONS LOG // H-03',
      hintBox: [
        'ALPHA executes before BRAVO.',
        'BRAVO executes before DELTA.',
        'DELTA executes before CHARLIE.',
      ],
      subPrompt: 'WHICH NODE EXECUTES THIRD?',
      options: ['ALPHA', 'BRAVO', 'CHARLIE', 'DELTA'],
      answer: 'DELTA',
      hint: 'Arrange all four nodes in the order forced by the three statements.',
      explanation: 'ALPHA → BRAVO → DELTA → CHARLIE. DELTA is third.',
    },
    {
      cat: 'BINARY SYSTEMS',
      title: 'BIT EXTRACTION',
      tag: 'H-04',
      streamText: 'PACKET // H-04',
      cipherText: '1101   0110',
      subPrompt: 'WHAT IS THE DECIMAL VALUE?',
      options: ['198', '214', '216', '226'],
      answer: '214',
      hint: 'Treat each 4-bit group as one hexadecimal digit.',
      explanation: '1101 = D (13) and 0110 = 6. Hex D6 equals decimal 214.',
    },
    {
      cat: 'CODE DEDUCTION',
      title: 'THREE CLUES',
      tag: 'H-05',
      streamText: 'LOCKER // H-05',
      hintBox: [
        '682 → one digit correct and correctly placed',
        '614 → one digit correct but wrongly placed',
        '206 → two digits correct but wrongly placed',
        '738 → no digit is correct',
      ],
      subPrompt: 'WHICH CODE OPENS THE LOCK?',
      options: ['042', '024', '062', '420'],
      answer: '042',
      hint: 'Start by eliminating every digit from 738, then apply the placement clues.',
      explanation: '7, 3 and 8 are excluded. The remaining placement clues resolve the code to 042.',
    },
  ],

  EXTREME: [
    {
      cat: 'PATTERN ANALYSIS',
      title: 'REGIME SHIFT',
      tag: 'X-01',
      streamText: 'QUANT STREAM // X-01',
      cipherText: '2   4   8   16   19   38   41   ?',
      metaInfo: 'THE RULE ALTERNATES AFTER 16',
      subPrompt: 'IDENTIFY THE NEXT VALUE',
      options: ['76', '79', '82', '84'],
      answer: '82',
      hint: 'After 16, the operations alternate +3 and ×2.',
      explanation: '16 + 3 = 19, ×2 = 38, +3 = 41, ×2 = 82.',
    },
    {
      cat: 'LOGIC MATRIX',
      title: 'VAULT ORDER',
      tag: 'X-02',
      streamText: 'VAULT PROTOCOL // X-02',
      hintBox: [
        'Four modules: CORE, DATA, LINK, GATE.',
        'LINK is first.',
        'CORE is immediately after LINK.',
        'DATA is immediately before GATE.',
      ],
      subPrompt: 'WHICH MODULE IS THIRD?',
      options: ['CORE', 'DATA', 'LINK', 'GATE'],
      answer: 'DATA',
      hint: 'Place LINK first, CORE immediately after it, then fit DATA immediately before GATE.',
      explanation: 'LINK → CORE → DATA → GATE. DATA is third.',
    },
    {
      cat: 'NUMBER LOGIC',
      title: 'STACKED OPERATIONS',
      tag: 'X-03',
      streamText: 'PROCESSOR // X-03',
      cipherText: '8² − 6 × 5 + 14 = ?',
      subPrompt: 'STANDARD PRECEDENCE REQUIRED',
      options: ['46', '48', '50', '52'],
      answer: '48',
      hint: 'Exponent first, multiplication second, then subtraction and addition.',
      explanation: '8² = 64 and 6×5 = 30. Therefore 64 − 30 + 14 = 48.',
    },
    {
      cat: 'CODE DEDUCTION',
      title: 'FOUR-DIGIT VAULT',
      tag: 'X-04',
      streamText: 'VAULT // X-04',
      hintBox: [
        'A four-digit code uses unique digits.',
        'Digit 1 is 6.',
        'Digit 2 is 3 more than digit 1.',
        'Digit 3 is 3 less than digit 2.',
        'Digit 4 is 3 less than digit 3.',
      ],
      subPrompt: 'SELECT THE CODE',
      options: ['6930', '9630', '6963', '6396'],
      answer: '6963',
      hint: 'Start with 6 and calculate each following digit exactly.',
      explanation: '6 → 9 → 6 → 3. The code is 6963.',
    },
    {
      cat: 'FINAL SECURITY',
      title: 'P-CELL CORE BREACH',
      tag: 'X-05',
      streamText: 'ALL SYSTEMS ONLINE // X-05',
      cipherText: '4   1   7   3',
      metaInfo: 'FINAL PROTOCOL',
      hintBox: [
        'Add the first and second digits.',
        'Multiply the result by 2.',
        'Add the third digit.',
        'Subtract the fourth digit.',
      ],
      subPrompt: 'ENTER THE FINAL VALUE',
      options: ['12', '13', '14', '17'],
      answer: '14',
      hint: 'Calculate it in this order: (4 + 1) × 2 + 7 − 3.',
      explanation: '(4 + 1) × 2 = 10. 10 + 7 − 3 = 14. FINAL ACCESS VALUE: 14.',
    },
  ],
}

export function rankCrack({ score, modeId: _modeId, strikes, win }) {
  if (!win) return 'ACCESS DENIED'
  if (strikes === 0 && score >= 1200) return 'CIPHER ARCHITECT'
  if (score >= 900) return 'OVERRIDE MASTER'
  if (score >= 600) return 'CLEARANCE GRANTED'
  return 'DECRYPT VALIDATED'
}
